on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate version tag
        id: version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          GIT_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "VERSION=1.0.${TIMESTAMP}-${GIT_SHA_SHORT}" >> $GITHUB_ENV
          echo "SHORT_VERSION=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "Generated version: $VERSION"
      - name: Build Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag ticket_logging_app:${VERSION} \
          --tag ticket_logging_app:latest \
          --build-arg APP_VERSION=${VERSION} \
          --build-arg DB_URL=b \
          --build-arg DB_USER=b \
          --build-arg DB_PASS=c \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg SERVER_PORT=e \
          --build-arg SMTP_HOST=f \
          --build-arg SMTP_USER=g \
          --build-arg SMTP_PASS=h \
          --build-arg SMTP_PORT=i
