on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag ticket_logging_app:${{ github.run_id }} \
          --tag ticket_logging_app:latest \
          --build-arg APP_VERSION=${VERSION} \
          --build-arg DB_URL=a  \
          --build-arg DB_USER=b \
          --build-arg DB_PASS=c \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg SERVER_PORT=e \
          --build-arg SMTP_HOST=f \
          --build-arg SMTP_USER=g \
          --build-arg SMTP_PASS=h \
          --build-arg SMTP_PORT=i
